# app.py
from flask import Flask, render_template

app = Flask(__name__)


@app.route('/')
def index():

    projects = [
        {
            'name': "Joyful Color AI",
            'url': "http://joyfulcolorai.com",
            'image': "/static/images/joyfulcolorai.png",
            'description': "An AI-powered tool for joyful color palettes.",
        },
        {
            'name': "Daily Bread AI",
            'url': "http://dailybreadai.com",
            'image': "/static/images/dailybreadai.png",
            'description': "Daily inspirational quotes generated by AI.",
        },
    ]

    return render_template('index.html', projects=projects)


if __name__ == '__main__':
    app.run(debug=True)
